name: Deploy to Staging

on:
  push:
    branches:
      - develop   # Change to your staging branch if needed

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install backend dependencies
        working-directory: ./server
        run: pnpm install

      - name: Run backend tests
        working-directory: ./server
        run: pnpm test

      - name: Lint backend
        working-directory: ./server
        run: pnpm lint

      - name: Build backend
        working-directory: ./server
        run: pnpm build

      - name: Install frontend dependencies
        working-directory: ./client
        run: pnpm install

      - name: Run frontend tests
        working-directory: ./client
        run: pnpm test

      - name: Lint frontend
        working-directory: ./client
        run: pnpm lint

      - name: Build frontend
        working-directory: ./client
        run: pnpm build

  deploy-backend:
    needs: test-and-build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render Staging
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID_STAGING }}
          api-key: ${{ secrets.RENDER_API_KEY_STAGING }}

  deploy-frontend:
    needs: test-and-build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Vercel Staging
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN_STAGING }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID_STAGING }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_STAGING }}
          working-directory: ./client
          vercel-args: '--prod' # Remove --prod for preview deployment